name: Build LaTeX document
on: [push]
jobs:
  build_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/thesis.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: thesis.pdf
  build_memo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/meterial/titleMemo.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: titleMemo.pdf
