name: Build LaTeX document
on: [push]
jobs:
  build_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile Thesis
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          working_directory: ./src
      - name: Compile Memo
        uses: xu-cheng/latex-action@v3
        with:
          root_file: titleMemo.tex
          working_directory: ./src/material
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: thesis_and_memo
          path: |
            ./src/thesis.pdf
            ./src/material/titleMemo.pdf
