name: Build LaTeX document
on: [push]
jobs:
  build_thesis:
    env:
      working-directory: ./src
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          working-directory: ${{env.working-directory}}
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: thesis.pdf
